#!/bin/bash

CONFIG_FILE=$1
TIMESTAMP=$(date +'%Y-%m-%d-%H-%M')

if [ "x${1}" = "x" ]; then
        CONFIG_FILE='/etc/jira-backup.conf'
        echo "Defaulting to Jira configuration from: ${CONFIG_FILE}"
fi

if [ -e ${CONFIG_FILE} ]; then
    source ${CONFIG_FILE}
else
    echo "Error: ${CONFIG_FILE} missing"
    exit 1
fi

ATTACHMENT_BACKUP_OUTPUT="${BACKUP_DIR}/${APP}-attachments-${TIMESTAMP}.tar"
DATABASE_DUMP_OUTPUT="${BACKUP_DIR}/${APP}-database-dump-${TIMESTAMP}.sql"


function setup() {
    if [ ! -d "${BACKUP_DIR}" ]; then
        echo "Creating ${BACKUP_DIR}"
        mkdir -p "${BACKUP_DIR}"
    fi
}

function backup_attachments() {
    echo "Backing up ${APP} attachments"
    /bin/tar -cpf ${ATTACHMENT_BACKUP_OUTPUT} ${ATTACHMENTS_PATH}
    echo "Created ${ATTACHMENT_BACKUP_OUTPUT}"
}

function dump_database() {
    echo "Dumping ${APP} database"
    /usr/bin/pg_dump -U "${DB_USER}" "${DB_NAME}" -h "${DB_HOST}" > "${DATABASE_DUMP_OUTPUT}"
    echo "Created ${DATABASE_DUMP_OUTPUT}"
}

function main() {
    echo "Backing up ${APP}"
    setup
    backup_attachments
    dump_database
}

main
